#!/bin/sh
NAME="php-fpm"
DESC="${NAME} deamon script"
DAEMON="/usr/sbin/php-fpm"
DAEMON_OPTS="--fpm-config=/etc/php5/fpm/php-fpm.conf"
#set this file to the same file as in your php-fpm.conf
PIDFILE="/var/run/${NAME}.pid"
QUIET="--quiet"
START_OPTS="--start ${QUIET} --background --exec ${DAEMON} -- ${DAEMON_OPTS}"
STOP_OPTS="--stop --pidfile ${PIDFILE}"

test -x $DAEMON || exit 0

set -e

case "$1" in
        start)
                echo -n "Starting $DESC: "
                export LD_LIBRARY_PATH="/usr/local/lib/"
                start-stop-daemon $START_OPTS
                echo "$NAME."
        ;;
        stop)
                echo -n "Stopping $DESC: "
                start-stop-daemon $STOP_OPTS
                echo "$NAME."
        ;;
        restart)
                echo -n "Restarting $DESC: "
                start-stop-daemon $STOP_OPTS
                sleep 1
                export LD_LIBRARY_PATH="/usr/local/lib/"
                start-stop-daemon $START_OPTS
                echo "$NAME."
        ;;
        *)
                N=/etc/init.d/$NAME
                echo "Usage: $N {start|stop|restart}" >&2
                exit 1
        ;;
esac

exit 0
